'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace DotNetNuke.Modules.RazorHost

    Partial Public Class EditScript

        '''<summary>
        '''toolTipManager control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents toolTipManager As Global.DotNetNuke.Web.UI.WebControls.DnnToolTipManager

        '''<summary>
        '''scriptsLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents scriptsLabel As Global.System.Web.UI.UserControl

        '''<summary>
        '''scriptList control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents scriptList As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''addNewButton control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents addNewButton As Global.DotNetNuke.UI.WebControls.CommandButton

        '''<summary>
        '''lblSourceFile control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblSourceFile As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''trSource control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents trSource As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''plSource control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plSource As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtSource control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtSource As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''currentScriptLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents currentScriptLabel As Global.System.Web.UI.UserControl

        '''<summary>
        '''isCurrentScript control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents isCurrentScript As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''cmdSave control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdSave As Global.DotNetNuke.UI.WebControls.CommandButton

        '''<summary>
        '''cmdSaveClose control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdSaveClose As Global.DotNetNuke.UI.WebControls.CommandButton

        '''<summary>
        '''cmdCancel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdCancel As Global.DotNetNuke.UI.WebControls.CommandButton
    End Class
End Namespace
